from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class EngineeringConcept:
    canonical: str
    category: str
    aliases: tuple[str, ...]
    causes: tuple[str, ...] = ()
    inspections: tuple[str, ...] = ()
    actions: tuple[str, ...] = ()
    risks: tuple[str, ...] = ()


CONCEPTS: tuple[EngineeringConcept, ...] = (
    EngineeringConcept("Steel Structure", "Equipment", ("steel structure", "kết cấu thép", "ket cau thep", "steel frame"), ("fit-up deviation", "wrong bolt sequence", "missing release hold point"), ("dimension survey", "weld map", "bolt torque record"), ("verify drawing revision", "control fit-up before welding", "hold point release"), ("structural nonconformance", "site erection delay")),
    EngineeringConcept("Welding", "Process", ("welding", "hàn", "han", "mối hàn", "duong han", "đường hàn"), ("poor joint preparation", "wrong WPS parameter", "contaminated surface"), ("VT", "WPS review", "welder qualification"), ("clean joint", "follow qualified WPS", "record weld parameters"), ("repair welding", "delayed inspection")),
    EngineeringConcept("SAW", "Process", ("saw", "submerged arc", "submerged arc welding", "hàn saw", "han saw"), ("wet flux", "rust", "oil", "incorrect travel speed", "low flux depth"), ("VT", "UT", "RT", "weld parameter log", "flux dryness check"), ("dry flux", "clean joint", "confirm voltage/current/travel speed", "control flux depth"), ("lack of fusion", "porosity", "slag inclusion")),
    EngineeringConcept("MIG welding", "Process", ("mig", "gmaw", "hàn mig", "han mig", "mối hàn mig"), ("dirty edge", "unstable shielding gas", "wrong torch angle"), ("VT", "MT", "gas flow check"), ("clean edge", "verify gas", "lock welding parameters"), ("porosity", "undercut", "rework")),
    EngineeringConcept("FCAW", "Process", ("fcaw", "flux cored arc", "hàn fcaw", "han fcaw"), ("wrong polarity", "damp wire", "slag not removed"), ("VT", "wire condition check", "polarity check"), ("clean between passes", "verify polarity", "store wire dry"), ("slag inclusion", "porosity")),
    EngineeringConcept("GTAW", "Process", ("gtaw", "tig", "hàn tig", "han tig"), ("contaminated tungsten", "poor shielding gas", "wrong filler selection"), ("VT", "PT", "gas flow check", "tungsten condition"), ("clean tungsten", "verify argon flow", "control arc length"), ("porosity", "lack of fusion", "tungsten inclusion")),
    EngineeringConcept("SMAW", "Process", ("smaw", "stick welding", "que hàn", "que han", "hàn que", "han que"), ("damp electrode", "wrong travel angle", "poor interpass cleaning"), ("VT", "MT", "electrode storage check"), ("dry electrodes", "clean slag between passes", "follow WPS"), ("slag inclusion", "undercut", "crack")),
    EngineeringConcept("Robot Welding", "Process", ("robot welding", "hàn robot", "han robot", "robot hàn"), ("torch TCP drift", "fixture repeatability issue", "wire feed instability"), ("program check", "TCP check", "fixture audit", "weld macro"), ("touch up TCP", "lock fixture datum", "verify wire feeding"), ("lack of fusion", "missed joint", "spatter")),
    EngineeringConcept("Laser Welding", "Process", ("laser welding", "hàn laser", "han laser"), ("wrong focus", "gap too large", "surface contamination"), ("focus check", "gap measurement", "macro section"), ("set focus", "control fit-up gap", "clean surface"), ("lack of penetration", "porosity", "crack")),
    EngineeringConcept("Wire", "Material", ("wire", "dây hàn", "day han", "welding wire"), ("wrong diameter", "rusted wire", "poor storage"), ("wire spool check", "diameter verification"), ("replace damaged wire", "protect wire from moisture"), ("arc instability",)),
    EngineeringConcept("Flux", "Material", ("flux", "thuốc hàn", "thuoc han"), ("wet flux", "contamination", "insufficient baking"), ("dryness check", "baking log", "flux depth check"), ("bake and store flux correctly", "discard contaminated flux"), ("porosity", "slag")),
    EngineeringConcept("Travel Speed", "Measurement", ("travel speed", "tốc độ hàn", "toc do han"), ("too fast", "too slow"), ("parameter log", "travel speed check"), ("set WPS range",), ("undercut", "low heat input")),
    EngineeringConcept("Voltage", "Measurement", ("voltage", "điện áp", "dien ap", "áp hàn", "ap han"), ("too high", "too low"), ("machine display check", "calibrated meter"), ("set approved WPS value",), ("spatter", "undercut")),
    EngineeringConcept("Current", "Measurement", ("current", "dòng hàn", "dong han", "amperage"), ("wrong current range", "unstable power"), ("clamp meter", "parameter log"), ("reset welding current",), ("lack of penetration")),
    EngineeringConcept("Stickout", "Measurement", ("stickout", "electrode extension", "tầm với dây", "tam voi day"), ("excessive stickout", "unstable hand technique"), ("stickout measurement",), ("set qualified stickout range",), ("spatter", "porosity")),
    EngineeringConcept("Heat Input", "Measurement", ("heat input", "nhiệt đầu vào", "nhiet dau vao"), ("low heat input", "excessive heat input"), ("WPS calculation",), ("balance current voltage and speed",), ("distortion", "lack of fusion")),
    EngineeringConcept("Porosity", "Defect", ("porosity", "rỗ khí", "ro khi", "rỗ hơi", "bọ khí"), ("moisture", "oil", "rust", "unstable shielding gas", "wet flux"), ("VT", "RT", "UT", "macro check"), ("remove defect", "clean surface", "reweld", "control moisture source"), ("rejection", "leak path")),
    EngineeringConcept("Undercut", "Defect", ("undercut", "cháy cạnh", "chay canh"), ("high voltage", "wrong travel speed", "poor torch angle"), ("VT", "weld gauge"), ("grind and repair", "adjust parameters"), ("fatigue crack initiation",)),
    EngineeringConcept("Slag Inclusion", "Defect", ("slag", "xỉ hàn", "xi han", "slag inclusion", "kẹt xỉ"), ("poor cleaning", "wrong angle", "low heat input"), ("VT", "UT", "interpass inspection"), ("remove slag between passes", "repair rejected weld"), ("inclusion rejection",)),
    EngineeringConcept("Lack of Fusion", "Defect", ("lack of fusion", "thiếu chảy cạnh", "thieu chay canh", "không ngấu cạnh"), ("low heat input", "dirty sidewall", "wrong torch angle"), ("UT", "macro", "WPS review"), ("remove unfused zone", "increase qualified heat input", "clean sidewall"), ("linear indication", "rejected weld")),
    EngineeringConcept("Lack of Penetration", "Defect", ("penetration", "ngấu", "thiếu ngấu", "thieu ngau", "lack of penetration"), ("low current", "bad fit-up", "low heat input"), ("UT", "macro test"), ("correct joint prep", "increase qualified heat input"), ("structural weakness",)),
    EngineeringConcept("Overlap", "Defect", ("overlap", "chồng mép", "chong mep"), ("travel speed too slow", "low current", "wrong torch angle"), ("VT", "weld profile gauge"), ("grind overlap", "repair profile", "reset technique"), ("stress concentration",)),
    EngineeringConcept("Arc Blow", "Defect", ("arc blow", "thổi lệch hồ quang", "thoi lech ho quang"), ("residual magnetism", "wrong ground clamp", "high DC current"), ("arc observation", "ground clamp check", "magnetism check"), ("move ground clamp", "reduce current within WPS", "demagnetize"), ("spatter", "lack of fusion")),
    EngineeringConcept("Burn Through", "Defect", ("burn through", "cháy thủng", "chay thung"), ("high heat input", "large root gap", "thin material"), ("VT", "RT", "root gap measurement"), ("remove defect", "reset root gap", "repair root pass"), ("leak path", "root rejection")),
    EngineeringConcept("Underfill", "Defect", ("underfill", "thiếu đầy", "thieu day"), ("insufficient deposit", "excessive grinding", "fast travel speed"), ("VT", "weld gauge"), ("add weld metal per WPS", "recheck size"), ("undersized weld",)),
    EngineeringConcept("Excess Reinforcement", "Defect", ("excess reinforcement", "gia cường quá mức", "gia cuong qua muc"), ("excess filler", "slow travel speed", "large weave"), ("VT", "weld reinforcement gauge"), ("grind to approved profile", "avoid undercut"), ("stress concentration", "fit-up interference")),
    EngineeringConcept("Weld Distortion", "Defect", ("weld distortion", "biến dạng hàn", "bien dang han", "cong vênh hàn"), ("unbalanced weld sequence", "weak fixture", "excess heat input"), ("dimension survey", "camber check", "flatness check"), ("correct weld sequence", "use fixture", "straighten by approved method"), ("erection mismatch",)),
    EngineeringConcept("Spatter", "Defect", ("spatter", "bắn tóe", "ban toe"), ("unstable arc", "wrong voltage", "long stickout"), ("VT", "parameter check", "gas flow check"), ("clean spatter", "reset WPS parameters", "control stickout"), ("paint defect", "extra grinding")),
    EngineeringConcept("Fit-up", "Process", ("fit-up", "fit up", "gá lắp", "ga lap", "lắp ghép", "lap ghep"), ("wrong gap", "misaligned member", "weak tack weld"), ("gap measurement", "diagonal check", "tack weld inspection"), ("correct gap before welding", "use fixture", "release fit-up hold point"), ("weld distortion", "rework")),
    EngineeringConcept("Assembly", "Process", ("assembly", "lắp ráp", "lap rap"), ("wrong sequence", "missing datum", "uncontrolled temporary support"), ("assembly checklist", "dimension check"), ("standardize assembly sequence", "verify datum before welding"), ("accumulated dimensional error",)),
    EngineeringConcept("Laser Cutting", "Process", ("laser", "laser cutting", "cắt laser", "cat laser", "máy cắt laser", "may cat laser"), ("dirty lens", "wrong focus", "assist gas pressure issue", "poor nesting discipline"), ("kerf inspection", "lens inspection", "nozzle centering", "5S area audit"), ("clean lens", "set focus", "verify gas", "separate input and output material"), ("bad kerf", "dross", "mixed parts")),
    EngineeringConcept("Plasma Cutting", "Process", ("plasma", "cắt plasma", "cat plasma"), ("worn electrode", "wrong air pressure", "poor grounding"), ("cut edge inspection", "consumable check", "air pressure check"), ("replace consumables", "set current and speed", "clean grounding point"), ("bevel error", "dross")),
    EngineeringConcept("Drilling", "Process", ("drilling", "khoan", "lỗ khoan", "lo khoan"), ("dull drill bit", "wrong feed", "poor clamping"), ("hole diameter check", "burr inspection", "fixture check"), ("replace drill bit", "control feed speed", "clamp material"), ("oval hole", "bolt fit issue")),
    EngineeringConcept("Saw Cutting", "Process", ("saw cutting", "cưa", "cua", "band saw", "máy cưa"), ("dull blade", "wrong feed rate", "poor material stop"), ("length check", "squareness check", "blade condition"), ("replace blade", "set stop block", "control feed"), ("length mismatch", "assembly gap")),
    EngineeringConcept("Rolling", "Process", ("rolling", "uốn lốc", "uon loc", "lốc tôn", "loc ton"), ("wrong roller setup", "springback", "uneven feed"), ("radius template", "profile check"), ("set roller gap", "trial piece", "control feed direction"), ("profile deviation",)),
    EngineeringConcept("Painting", "Process", ("painting", "sơn", "son", "coating", "sơn phủ", "son phu"), ("humidity", "poor blast profile", "dust", "oil contamination", "insufficient curing"), ("DFT", "adhesion", "dew point", "surface cleanliness"), ("control surface prep and environment", "repair failed coating area"), ("corrosion", "recoat", "client rejection")),
    EngineeringConcept("Blasting", "Process", ("blasting", "blast", "phun bi", "phun cát", "phun cat", "sa 2.5"), ("wrong abrasive", "oil contamination", "low profile", "flash rust"), ("profile tape", "surface cleanliness check", "salt contamination test"), ("reset blasting parameters", "protect blasted surface before coating"), ("poor coating adhesion", "early corrosion")),
    EngineeringConcept("DFT", "Measurement", ("dft", "dry film thickness", "thickness", "độ dày màng sơn", "do day mang son"), ("uneven application", "wrong spray distance"), ("DFT gauge", "calibration foil", "spot reading map"), ("repair low or high DFT areas", "record DFT map"), ("coating failure",)),
    EngineeringConcept("Adhesion", "Measurement", ("adhesion", "độ bám dính", "do bam dinh", "bong tróc", "bong troc", "peeling"), ("contamination", "wrong profile", "painting over condensation"), ("adhesion test", "cross-cut test", "pull-off test"), ("reblast and repaint failed area", "hold painting until substrate is clean"), ("peeling", "corrosion exposure")),
    EngineeringConcept("Blast Profile", "Measurement", ("blast profile", "profile", "độ nhám", "do nham", "surface profile"), ("wrong abrasive", "low profile", "spent abrasive"), ("profile tape", "comparator check"), ("reset abrasive mix", "verify profile before primer"), ("poor coating adhesion",)),
    EngineeringConcept("Humidity", "Measurement", ("humidity", "độ ẩm", "do am", "dew point", "điểm sương", "diem suong"), ("high humidity", "surface condensation"), ("dew point meter", "steel temperature check"), ("hold painting until condition is acceptable",), ("blistering", "peeling")),
    EngineeringConcept("Corrosion", "Defect", ("corrosion", "ăn mòn", "an mon", "gỉ", "gi"), ("coating breakdown", "salt contamination", "water trap"), ("visual inspection", "DFT check", "salt test"), ("remove corrosion", "restore coating system", "improve drainage"), ("section loss", "repaint cost")),
    EngineeringConcept("Crane", "Machine", ("crane", "cẩu", "cau", "overhead crane", "cầu trục", "cau truc"), ("overload", "poor limit switch", "worn wire rope"), ("load test record", "wire rope inspection", "limit switch test"), ("isolate crane", "repair lifting gear", "enforce lifting plan"), ("dropped load", "line stoppage")),
    EngineeringConcept("Compressor", "Machine", ("compressor", "máy nén khí", "may nen khi", "air compressor"), ("clogged filter", "high temperature", "low oil", "leakage"), ("pressure record", "temperature check", "oil level", "air leak test"), ("clean filter", "fix leaks", "restore cooling and oil level"), ("tool downtime", "energy waste")),
    EngineeringConcept("Gearbox", "Machine", ("gearbox", "hộp số", "hop so", "reducer"), ("low oil", "gear wear", "misalignment", "overload"), ("oil level", "vibration", "temperature", "backlash check"), ("change oil", "inspect gear", "align drive train"), ("drive failure",)),
    EngineeringConcept("Motor", "Machine", ("motor", "động cơ", "dong co"), ("overload", "poor cooling", "bearing fault", "phase imbalance"), ("current", "temperature", "vibration", "insulation resistance"), ("clean cooling path", "check load", "inspect bearing", "tighten terminals"), ("overheat", "unplanned stop")),
    EngineeringConcept("Hydraulic", "System", ("hydraulic", "thủy lực", "thuy luc"), ("oil contamination", "low pressure", "seal leakage"), ("pressure gauge", "oil cleanliness", "leak inspection"), ("filter oil", "replace seal", "set pressure relief valve"), ("loss of force", "slip hazard")),
    EngineeringConcept("Pneumatic", "System", ("pneumatic", "khí nén", "khi nen"), ("air leak", "water in line", "low pressure"), ("pressure check", "leak test", "FRL inspection"), ("repair leak", "drain water", "set regulator"), ("slow cylinder", "energy waste")),
    EngineeringConcept("Electrical", "System", ("electrical", "điện", "dien", "tủ điện", "tu dien"), ("loose terminal", "overload", "wrong protection setting"), ("thermal scan", "current check", "terminal torque"), ("tighten terminal", "verify protection", "label circuit"), ("fire risk", "unexpected stop")),
    EngineeringConcept("PLC", "Component", ("plc", "programmable logic controller", "điều khiển plc", "dieu khien plc"), ("sensor fault", "logic interlock", "loose input signal"), ("I/O check", "alarm history", "program backup"), ("verify sensor", "restore interlock", "back up PLC program"), ("automation stop",)),
    EngineeringConcept("Bearing", "Component", ("bearing", "ổ bi", "o bi", "bạc đạn", "bac dan"), ("poor lubrication", "misalignment", "dust", "overload"), ("vibration", "temperature", "noise", "grease condition"), ("lubricate", "align", "replace bearing", "protect seal"), ("machine stop", "shaft damage")),
    EngineeringConcept("Reducer", "Component", ("reducer", "hộp giảm tốc", "hop giam toc"), ("low oil", "worn gear", "loose base"), ("oil level check", "vibration reading", "bolt tightness"), ("change oil", "tighten base", "inspect gear mesh"), ("drive trip", "gear tooth failure")),
    EngineeringConcept("Chain", "Component", ("chain", "xích", "xich"), ("poor lubrication", "elongation", "wrong tension"), ("chain elongation", "tension check", "sprocket wear"), ("lubricate chain", "adjust tension", "replace worn chain"), ("conveyor jam",)),
    EngineeringConcept("Coupling", "Component", ("coupling", "khớp nối", "khop noi"), ("misalignment", "worn insert", "loose key"), ("laser alignment", "coupling gap", "key inspection"), ("align shafts", "replace insert", "tighten set screw"), ("bearing damage", "vibration")),
    EngineeringConcept("Pump", "Machine", ("pump", "bơm", "bom"), ("cavitation", "seal leakage", "blocked suction"), ("flow check", "pressure check", "seal inspection"), ("clear suction", "prime pump", "replace seal"), ("low flow", "motor overload")),
    EngineeringConcept("Valve", "Component", ("valve", "van"), ("sticking valve", "leakage", "wrong position"), ("leak test", "stroke check", "tag verification"), ("clean valve", "repair seal", "lock correct position"), ("pressure loss", "unsafe isolation")),
    EngineeringConcept("Cylinder", "Component", ("cylinder", "xi lanh", "xylanh"), ("seal wear", "rod misalignment", "low pressure"), ("stroke check", "leak inspection", "rod condition"), ("replace seal", "align rod", "restore pressure"), ("weak clamping", "slow movement")),
    EngineeringConcept("Conveyor", "Machine", ("conveyor", "băng tải", "bang tai"), ("belt mistracking", "bad roller", "chain wear"), ("tracking check", "roller inspection", "tension check"), ("align pulley", "replace roller", "set belt tension"), ("material spill", "production stop")),
    EngineeringConcept("Grinding", "Process", ("grinding", "mài", "mai", "mài sửa", "may mai", "máy mài"), ("over grinding", "wrong disc", "brush wear", "dust ingress"), ("profile check", "disc inspection", "brush and bearing check"), ("control removal depth", "replace disc", "clean ventilation path"), ("dimension loss", "surface damage", "hand injury")),
    EngineeringConcept("5S", "Process", ("5s", "kaizen", "lean", "sàng lọc", "sắp xếp", "sạch sẽ", "san sang", "sap xep", "sach se"), ("undefined location", "weak daily audit", "mixed WIP", "unclear owner"), ("5S audit", "shadow board check", "red tag review", "area photo standard"), ("sort set shine standardize sustain", "mark material flow", "assign area owner"), ("waiting waste", "trip hazard")),
    EngineeringConcept("Kaizen", "Process", ("kaizen", "cải tiến", "cai tien"), ("small losses not measured", "operator feedback ignored"), ("loss observation", "before-after check"), ("run small improvement cycle", "standardize the new method"), ("recurring waste",)),
    EngineeringConcept("Lean", "Process", ("lean", "tinh gọn", "tinh gon", "waste"), ("waiting waste", "transport waste", "overprocessing"), ("value stream walk", "cycle time check"), ("remove waiting point", "balance flow", "visualize WIP limit"), ("long lead time",)),
    EngineeringConcept("TPM", "Process", ("tpm", "total productive maintenance", "bảo trì tự quản", "bao tri tu quan"), ("reactive maintenance", "missing autonomous checks"), ("PM checklist", "OEE loss review", "abnormality tag"), ("plan preventive maintenance", "train operator daily checks"), ("downtime", "repeat failure")),
    EngineeringConcept("QAQC", "Department", ("qaqc", "qa/qc", "qc", "quality control", "kiểm tra chất lượng", "kiem tra chat luong"), ("unclear acceptance criteria", "late inspection"), ("ITP review", "hold point", "inspection report"), ("define acceptance criteria", "release by evidence"), ("client rejection",)),
    EngineeringConcept("NDT", "Process", ("ndt", "non destructive testing", "kiểm tra không phá hủy", "kiem tra khong pha huy", "ut", "mt", "pt", "rt"), ("wrong method selection", "late defect discovery"), ("NDT plan", "qualified technician", "report traceability"), ("select correct NDT method", "repair and retest rejected area"), ("hidden defect", "schedule delay")),
    EngineeringConcept("AWS", "Standard", ("aws", "aws d1.1"), ("unqualified WPS", "missing welder qualification"), ("WPS/PQR review", "welder certificate"), ("align weld control to AWS requirement",), ("audit finding",)),
    EngineeringConcept("ISO", "Standard", ("iso", "iso 9001", "iso 3834"), ("weak documented process", "missing traceability"), ("procedure audit", "record review"), ("standardize procedure and records",), ("system nonconformance",)),
    EngineeringConcept("AISC", "Standard", ("aisc",), ("nonconforming structural tolerance",), ("fabrication tolerance check",), ("align fabrication control with AISC tolerance",), ("erection fit issue",)),
    EngineeringConcept("EN1090", "Standard", ("en1090", "en 1090", "en-1090"), ("missing execution class control",), ("FPC record", "welding coordination review"), ("control execution class and inspection records",), ("CE compliance risk",)),
    EngineeringConcept("Anchor Bolt", "Component", ("anchor bolt", "bu lông neo", "bu long neo", "anchor"), ("wrong projection", "mislocation", "missing template"), ("survey position", "projection check", "thread inspection"), ("correct anchor position", "protect thread", "verify template"), ("erection delay", "base plate rework")),
    EngineeringConcept("Base Plate", "Component", ("base plate", "bản mã chân cột", "ban ma chan cot", "đế cột", "de cot"), ("uneven grout", "poor leveling", "wrong hole position"), ("level survey", "hole alignment", "grout inspection"), ("shim correctly", "verify level", "release before torque"), ("column alignment issue",)),
    EngineeringConcept("Bolt Torque", "Measurement", ("bolt torque", "siết bu lông", "siet bu long", "torque"), ("wrong torque sequence", "uncalibrated wrench"), ("torque wrench calibration", "torque record"), ("tighten by approved sequence", "record final torque"), ("joint slip", "loose connection")),
    EngineeringConcept("Shim", "Component", ("shim", "canh shim", "chêm", "chem"), ("wrong shim stack", "soft bearing surface"), ("shim thickness check", "contact check"), ("use approved shim pack", "verify bearing contact"), ("leveling error",)),
    EngineeringConcept("Alignment", "Measurement", ("alignment", "căn chỉnh", "can chinh", "đồng tâm", "dong tam"), ("misalignment", "soft foot", "loose base"), ("laser alignment", "straight edge", "soft-foot check"), ("align coupling and shaft", "tighten base after alignment"), ("bearing damage", "vibration")),
    EngineeringConcept("Vibration", "Measurement", ("vibration", "rung", "độ rung", "do rung"), ("imbalance", "misalignment", "bearing fault", "loose foundation"), ("vibration reading", "trend review"), ("balance rotor", "align drive", "inspect bearing"), ("fatigue", "downtime")),
    EngineeringConcept("Lubrication", "Process", ("lubrication", "bôi trơn", "boi tron", "grease", "dầu bôi trơn"), ("wrong grease", "low grease", "contaminated oil", "overgreasing"), ("lubrication log", "oil level", "grease condition"), ("apply correct lubricant on schedule", "clean lubrication point"), ("bearing heat", "gear wear")),
    EngineeringConcept("Material Handling", "Process", ("material handling", "nâng hạ", "nang ha", "xếp dỡ", "xep do", "vận chuyển vật tư"), ("poor lifting plan", "unprotected coating", "mixed materials"), ("lifting plan review", "sling inspection", "material tag check"), ("separate material lanes", "protect coating", "use approved lifting point"), ("impact damage", "struck-by risk")),
    EngineeringConcept("Safety", "Risk", ("safety", "an toàn", "an toan", "hse", "ppe"), ("missing guard", "poor housekeeping", "uncontrolled energy"), ("PPE check", "JSA", "LOTO verification"), ("stop unsafe work", "install guard", "brief crew before restart"), ("injury", "near miss")),
    EngineeringConcept("Dross", "Defect", ("dross", "ba via", "bavia", "xỉ cắt", "xi cat"), ("wrong cutting speed", "worn consumable", "wrong focus"), ("edge inspection", "sample cut", "parameter review"), ("reset cut parameter", "replace consumable", "clean edge"), ("fit-up interference",)),
    EngineeringConcept("Blistering", "Defect", ("blistering", "phồng rộp", "phong rop"), ("trapped moisture", "salt contamination", "painting over dew point"), ("adhesion test", "holiday inspection", "dew point record"), ("remove failed paint", "clean substrate", "repaint under controlled condition"), ("coating breakdown",)),
)


def all_concepts() -> tuple[EngineeringConcept, ...]:
    return CONCEPTS
