
from pathlib import Path
from docx import Document

from hgpt_ai_os.planner.planner_engine import PlannerEngine
from hgpt_ai_os.knowledge.engine import KnowledgeEngine


class LucidOrchestrator:

    def run(self):

        planner = PlannerEngine()
        knowledge = KnowledgeEngine()

        task = planner.next_task()

        if not task:
            print("No TODO task.")
            return

        planner.update_status(task["row"], "RUNNING")

        out = Path("outputs/marketing") / f"Day{int(task['day']):03d}"
        out.mkdir(parents=True, exist_ok=True)

        files = [
            "facebook.docx",
            "tiktok.docx",
            "seo.docx",
            "image_prompt.docx",
            "video_prompt.docx",
            "approval_checklist.docx",
        ]

        for name in files:
            doc = Document()
            doc.add_heading(task["topic"], level=1)
            doc.add_paragraph(f"Platform: {task['platform']}")
            doc.add_paragraph("Generated by HGPT Lucid Auto")
            doc.save(out / name)

        planner.update_status(task["row"], "GENERATED")

        print("=" * 60)
        print("HGPT LUCID AUTO")
        print("=" * 60)
        print("Task :", task["topic"])
        print("Status : GENERATED")
        print("Output :", out)


if __name__ == "__main__":
    LucidOrchestrator().run()
